### ISSUE TITLE
Ébauche de plan

### ISSUE THREAD

**Issue by AbcSxyZ** [Open-Models/Brique#1]
Je propose un début de plan pour construire le contenu de la brique de connaissance.

L'objectif est dans un premier temps de faire comprendre le phénomène des modèles ouverts et de chercher à montrer comme ces différents projets ouverts se structurent, tout en s'appuyant sur exemples de ce qui existe déjà.

Pour le moment j'ai ce plan en tête qui me semble permettre de faire le tour.

## Plan

- [x] Définition du terme "modèles ouverts"
- [ ] Liste des modèles ouverts (https://github.com/Open-Models/Brique/issues/2)
- [ ] Liste de projets (https://github.com/Open-Models/Brique/issues/3)
- [x] Histoire des modèles ouverts
- [ ] Méthode structuration d'un projet ouvert (https://github.com/Open-Models/Brique/issues/4)
- [ ] Modèles économiques
